POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "teste de codigo",
  "details": "sera que funcionou?",
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/542d1846-89d6-4d5a-87b4-0548a4f6c2a7/attendees
Content-Type: application/json

{
  "name": "Tiago Henrique",
  "email": "lironnick@gmail.com"
}

###

GET http://localhost:3333/events/542d1846-89d6-4d5a-87b4-0548a4f6c2a7
###

GET http://localhost:3333/attendees/1/badge
###

GET http://localhost:3333/attendees/10202/check-in

###

GET http://localhost:3333/events/542d1846-89d6-4d5a-87b4-0548a4f6c2a7/attendees?query=tiago